keys:
  - &admin age19wvqtn4ju6k4vs8fxr34unl6xx4cv04jw0lx9ps20xlde927zfssgl4qke
  - &nixarr age12xf2kpcjjjuuh03gu5s2u3jf7e7654efz7uxv537mnyt2hs8f9hq6fucje

creation_rules:
  - path_regex: secrets/nixarr\.yaml$
    key_groups:
      - age:
          - *admin
          - *nixarr
